Updated modules required in hitcounter.js
In Node.js v18+, using aws-sdk will cause a Runtime.ImportModuleError:  Cannot find module 'aws-sdk'.
Change to @aws-sdk/client-dynamodb, @aws-sdk/client-lambda will fix this error.